const mongoose = require('mongoose');

const carSchema = new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    mode:{
        type:String,
        required:true,
    },
    model:{
        type:String,
        required:true,
    },
    body:{
        type:String,
        required:true,
    },
    year:{
        type:Number,
        required:true,
    },
    condition:{
        type:String,
        required:true,
    },
    stock_number:{
        type:Number,
    },
    vin_number:{
        type:Number,
    },
    mileage:{
        type:Number,
    },
    transmission:{
        type:String,
        required:true,
    },
    cylinders:{
        type:String,
        required:true,
    },
    engine:{
        type:String,
    },
    fuel_type:{
        type:String,
        required:true,
    },
    drive_type:{
        type:String,
        required:true,
    },
    door:{
        type:Number,
    },
    color:{
        type:String,
    },
    seat:{
        type:String,
    },
    city_mpg:{
        type:String,
    },
    highway_mpg:{
        type:String,
    },
    description:{
        type:String,
        required:true,
    }
})